port: 4730
enableSSL: false
debugging: true
hostName: localhost
jobPersistenceEngine:
  engine: mysql
  dbSQL:
    host: localhost
    port: 3306
    dbName: gearman
    user: root
    password: 1234
    table: gearman_jobs_00
cronJobpersistenceEngine:
  engine: mysql
  dbSQL:
    host: localhost
    port: 3306
    dbName: gearman
    user: root
    password: 1234
    table: gearman_Cronjobs_00
exceptionStorageEngine:
  engine: mysql
  dbSQL:
    host: localhost
    port: 3306
    dbName: gearman
    user: root
    password: 1234
    table: gearman_Exception_00