port: 4730
enableSSL: false
debugging: true
hostName: localhost
persistenceEngine:
  engine: mysql
  dbSQL:
    host: localhost
    port: 3306
    dbName: gearman
    user: root
    password: 899899AbC
    table: gearman_00
exceptionStore:
  engine: memory